# Generated by Django 6.1.1 on 2026-09-06 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام رستوران')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('hero_title', models.CharField(default='Taste the Difference', max_length=200, verbose_name='عنوان اصلی')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='متن اصلی')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='عکس اصلی')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='اینستاگرام')),
            ],
            options={
                'verbose_name': 'اطلاعات رستوران',
                'verbose_name_plural': 'اطلاعات رستوران',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام غذا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='عکس غذا')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود است')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
            },
        ),
    ]
